
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ecs_cluster
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    configuration = optional(object({
        execute_command_configuration = optional(object({
            kms_key_id = optional(string)
            log_configuration = optional(object({
                cloud_watch_encryption_enabled = optional(bool)
                cloud_watch_log_group_name = optional(string)
                s3_bucket_name = optional(string)
                s3_bucket_encryption_enabled = optional(bool)
                s3_key_prefix = optional(string)
            }))
            logging = optional(string)
        }))
    }))
    name = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_ecs_cluster" "this" {
  configuration = var.values.configuration
  name = var.values.name
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ecs_cluster.this.arn
}

