######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appconfig_configuration_profile
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    application_id = optional(string)
    description = optional(string)
    location_uri = optional(string)
    name = optional(string)
    retrieval_role_arn = optional(string)
    tags = optional(map(string))
    type = optional(string)
    validator = optional(set(object({
        content = optional(string)
        type = optional(string)
    })))
  })
}

resource "aws_appconfig_configuration_profile" "this" {

  {{- if $.Values.application_id }}
  application_id = var.values.application_id
  {{- end }}
  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}
  {{- if $.Values.location_uri }}
  location_uri = var.values.location_uri
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.retrieval_role_arn }}
  retrieval_role_arn = var.values.retrieval_role_arn
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}
  {{- if $.Values.type }}
  type = var.values.type
  {{- end }}
  {{- if $.Values.validator }}
  dynamic "validator" {
    for_each = var.values.validator[*]
    content {
      content = validator.value.content
      type = validator.value.type
    }
  }
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appconfig_configuration_profile.this.arn
}

output "configuration_profile_id" {
    value = aws_appconfig_configuration_profile.this.configuration_profile_id
}

output "retrieval_role_arn" {
    value = aws_appconfig_configuration_profile.this.retrieval_role_arn
}

