
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appconfig_configuration_profile
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    application_id = optional(string)
    description = optional(string)
    location_uri = optional(string)
    name = optional(string)
    retrieval_role_arn = optional(string)
    tags = optional(map(string))
    type = optional(string)
    validator = optional(set(any))
  })
}

resource "aws_appconfig_configuration_profile" "this" {
  application_id = var.values.application_id
  description = var.values.description
  location_uri = var.values.location_uri
  name = var.values.name
  retrieval_role_arn = var.values.retrieval_role_arn
  tags = var.values.tags
  type = var.values.type
  validator = var.values.validator
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appconfig_configuration_profile.this.arn
}

output "configuration_profile_id" {
    value = aws_appconfig_configuration_profile.this.configuration_profile_id
}

output "retrieval_role_arn" {
    value = aws_appconfig_configuration_profile.this.retrieval_role_arn
}

