######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ecs_tag
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    key = optional(string)
    resource_arn = optional(string)
    value = optional(string)
  })
}

resource "aws_ecs_tag" "this" {

  {{- if $.Values.key }}
  key = var.values.key
  {{- end }}
  {{- if $.Values.resource_arn }}
  resource_arn = var.values.resource_arn
  {{- end }}
  {{- if $.Values.value }}
  value = var.values.value
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "resource_arn" {
    value = aws_ecs_tag.this.resource_arn
}

