######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_lb_listener
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    alpn_policy = optional(string)
    certificate_arn = optional(string)
    default_action = optional(list(object({
        type = optional(string)
        authenticate_cognito = optional(list(object({
            user_pool_domain = optional(string)
            authentication_request_extra_params = optional(map(string))
            on_unauthenticated_request = optional(string)
            scope = optional(string)
            session_cookie_name = optional(string)
            session_timeout = optional(number)
            user_pool_arn = optional(string)
            user_pool_client_id = optional(string)
        })))
        authenticate_oidc = optional(list(object({
            authorization_endpoint = optional(string)
            client_secret = optional(string)
            issuer = optional(string)
            session_cookie_name = optional(string)
            token_endpoint = optional(string)
            user_info_endpoint = optional(string)
            authentication_request_extra_params = optional(map(string))
            on_unauthenticated_request = optional(string)
            scope = optional(string)
            session_timeout = optional(number)
            client_id = optional(string)
        })))
        fixed_response = optional(list(object({
            content_type = optional(string)
            message_body = optional(string)
            status_code = optional(string)
        })))
        forward = optional(list(object({
            target_group = optional(set(object({
                arn = optional(string)
                weight = optional(number)
            })))
            stickiness = optional(list(object({
                duration = optional(number)
                enabled = optional(bool)
            })))
        })))
        order = optional(number)
        redirect = optional(list(object({
            host = optional(string)
            path = optional(string)
            port = optional(string)
            protocol = optional(string)
            query = optional(string)
            status_code = optional(string)
        })))
        target_group_arn = optional(string)
    })))
    load_balancer_arn = optional(string)
    port = optional(number)
    tags = optional(map(string))
  })
}

resource "aws_lb_listener" "this" {

  {{- if $.Values.alpn_policy }}
  alpn_policy = var.values.alpn_policy
  {{- end }}
  {{- if $.Values.certificate_arn }}
  certificate_arn = var.values.certificate_arn
  {{- end }}
  {{- if $.Values.default_action }}
  dynamic "default_action" {
    for_each = var.values.default_action[*]
    content {
      dynamic "authenticate_oidc" {
        for_each = default_action.value.authenticate_oidc[*]
        content {
          client_id = authenticate_oidc.value.client_id
          on_unauthenticated_request = authenticate_oidc.value.on_unauthenticated_request
          scope = authenticate_oidc.value.scope
          session_timeout = authenticate_oidc.value.session_timeout
          authentication_request_extra_params = authenticate_oidc.value.authentication_request_extra_params
          authorization_endpoint = authenticate_oidc.value.authorization_endpoint
          client_secret = authenticate_oidc.value.client_secret
          issuer = authenticate_oidc.value.issuer
          session_cookie_name = authenticate_oidc.value.session_cookie_name
          token_endpoint = authenticate_oidc.value.token_endpoint
          user_info_endpoint = authenticate_oidc.value.user_info_endpoint
        }
      }
      dynamic "fixed_response" {
        for_each = default_action.value.fixed_response[*]
        content {
          content_type = fixed_response.value.content_type
          message_body = fixed_response.value.message_body
          status_code = fixed_response.value.status_code
        }
      }
      dynamic "forward" {
        for_each = default_action.value.forward[*]
        content {
          dynamic "stickiness" {
            for_each = forward.value.stickiness[*]
            content {
              enabled = stickiness.value.enabled
              duration = stickiness.value.duration
            }
          }
          dynamic "target_group" {
            for_each = forward.value.target_group[*]
            content {
              arn = target_group.value.arn
              weight = target_group.value.weight
            }
          }
        }
      }
      order = default_action.value.order
      dynamic "redirect" {
        for_each = default_action.value.redirect[*]
        content {
          status_code = redirect.value.status_code
          host = redirect.value.host
          path = redirect.value.path
          port = redirect.value.port
          protocol = redirect.value.protocol
          query = redirect.value.query
        }
      }
      target_group_arn = default_action.value.target_group_arn
      type = default_action.value.type
      dynamic "authenticate_cognito" {
        for_each = default_action.value.authenticate_cognito[*]
        content {
          on_unauthenticated_request = authenticate_cognito.value.on_unauthenticated_request
          scope = authenticate_cognito.value.scope
          session_cookie_name = authenticate_cognito.value.session_cookie_name
          session_timeout = authenticate_cognito.value.session_timeout
          user_pool_arn = authenticate_cognito.value.user_pool_arn
          user_pool_client_id = authenticate_cognito.value.user_pool_client_id
          user_pool_domain = authenticate_cognito.value.user_pool_domain
          authentication_request_extra_params = authenticate_cognito.value.authentication_request_extra_params
        }
      }
    }
  }
  {{- end }}
  {{- if $.Values.load_balancer_arn }}
  load_balancer_arn = var.values.load_balancer_arn
  {{- end }}
  {{- if $.Values.port }}
  port = var.values.port
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_lb_listener.this.arn
}

output "certificate_arn" {
    value = aws_lb_listener.this.certificate_arn
}

output "load_balancer_arn" {
    value = aws_lb_listener.this.load_balancer_arn
}

output "protocol" {
    value = aws_lb_listener.this.protocol
}

output "ssl_policy" {
    value = aws_lb_listener.this.ssl_policy
}

