######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_transit_gateway_vpc_attachment_accepter
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    tags = optional(map(string))
    transit_gateway_attachment_id = optional(string)
    transit_gateway_default_route_table_association = optional(bool)
    transit_gateway_default_route_table_propagation = optional(bool)
  })
}

resource "aws_ec2_transit_gateway_vpc_attachment_accepter" "this" {

  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}
  {{- if $.Values.transit_gateway_attachment_id }}
  transit_gateway_attachment_id = var.values.transit_gateway_attachment_id
  {{- end }}
  {{- if $.Values.transit_gateway_default_route_table_association }}
  transit_gateway_default_route_table_association = var.values.transit_gateway_default_route_table_association
  {{- end }}
  {{- if $.Values.transit_gateway_default_route_table_propagation }}
  transit_gateway_default_route_table_propagation = var.values.transit_gateway_default_route_table_propagation
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "appliance_mode_support" {
    value = aws_ec2_transit_gateway_vpc_attachment_accepter.this.appliance_mode_support
}

output "dns_support" {
    value = aws_ec2_transit_gateway_vpc_attachment_accepter.this.dns_support
}

output "ipv6_support" {
    value = aws_ec2_transit_gateway_vpc_attachment_accepter.this.ipv6_support
}

output "transit_gateway_id" {
    value = aws_ec2_transit_gateway_vpc_attachment_accepter.this.transit_gateway_id
}

output "vpc_id" {
    value = aws_ec2_transit_gateway_vpc_attachment_accepter.this.vpc_id
}

output "vpc_owner_id" {
    value = aws_ec2_transit_gateway_vpc_attachment_accepter.this.vpc_owner_id
}

