
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_service_linked_role
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    aws_service_name = optional(string)
    custom_suffix = optional(string)
    description = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_iam_service_linked_role" "this" {
  aws_service_name = var.values.aws_service_name
  custom_suffix = var.values.custom_suffix
  description = var.values.description
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_iam_service_linked_role.this.arn
}

output "create_date" {
    value = aws_iam_service_linked_role.this.create_date
}

output "name" {
    value = aws_iam_service_linked_role.this.name
}

output "path" {
    value = aws_iam_service_linked_role.this.path
}

output "unique_id" {
    value = aws_iam_service_linked_role.this.unique_id
}

