######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appstream_directory_config
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    directory_name = optional(string)
    organizational_unit_distinguished_names = optional(set(string))
    service_account_credentials = optional(list(object({
        account_password = optional(string)
        account_name = optional(string)
    })))
  })
}

resource "aws_appstream_directory_config" "this" {

  {{- if $.Values.directory_name }}
  directory_name = var.values.directory_name
  {{- end }}
  {{- if $.Values.organizational_unit_distinguished_names }}
  organizational_unit_distinguished_names = var.values.organizational_unit_distinguished_names
  {{- end }}
  {{- if $.Values.service_account_credentials }}
  service_account_credentials = var.values.service_account_credentials
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "created_time" {
    value = aws_appstream_directory_config.this.created_time
}

