######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appsync_domain_name
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    certificate_arn = optional(string)
    description = optional(string)
    domain_name = optional(string)
  })
}

resource "aws_appsync_domain_name" "this" {

  {{- if $.Values.certificate_arn }}
  certificate_arn = var.values.certificate_arn
  {{- end }}
  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}
  {{- if $.Values.domain_name }}
  domain_name = var.values.domain_name
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "appsync_domain_name" {
    value = aws_appsync_domain_name.this.appsync_domain_name
}

output "certificate_arn" {
    value = aws_appsync_domain_name.this.certificate_arn
}

output "hosted_zone_id" {
    value = aws_appsync_domain_name.this.hosted_zone_id
}

