
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appsync_graphql_api
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    additional_authentication_provider = optional(object({
        authentication_type = optional(string)
        openid_connect_config = optional(object({
            issuer = optional(string)
            auth_ttl = optional(number)
            client_id = optional(string)
            iat_ttl = optional(number)
        }))
        user_pool_config = optional(object({
            app_id_client_regex = optional(string)
            aws_region = optional(string)
            user_pool_id = optional(string)
        }))
        lambda_authorizer_config = optional(object({
            authorizer_result_ttl_in_seconds = optional(number)
            authorizer_uri = optional(string)
            identity_validation_expression = optional(string)
        }))
    }))
    authentication_type = optional(string)
    lambda_authorizer_config = optional(object({
        authorizer_result_ttl_in_seconds = optional(number)
        authorizer_uri = optional(string)
        identity_validation_expression = optional(string)
    }))
    log_config = optional(object({
        cloudwatch_logs_role_arn = optional(string)
        field_log_level = optional(string)
        exclude_verbose_content = optional(bool)
    }))
    name = optional(string)
    openid_connect_config = optional(object({
        auth_ttl = optional(number)
        client_id = optional(string)
        iat_ttl = optional(number)
        issuer = optional(string)
    }))
    schema = optional(string)
    tags = optional(map(string))
    user_pool_config = optional(object({
        app_id_client_regex = optional(string)
        aws_region = optional(string)
        default_action = optional(string)
        user_pool_id = optional(string)
    }))
    xray_enabled = optional(bool)
  })
}

resource "aws_appsync_graphql_api" "this" {
  additional_authentication_provider = var.values.additional_authentication_provider
  authentication_type = var.values.authentication_type
  lambda_authorizer_config = var.values.lambda_authorizer_config
  log_config = var.values.log_config
  name = var.values.name
  openid_connect_config = var.values.openid_connect_config
  schema = var.values.schema
  tags = var.values.tags
  user_pool_config = var.values.user_pool_config
  xray_enabled = var.values.xray_enabled
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appsync_graphql_api.this.arn
}

