
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appstream_fleet
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    compute_capacity = optional(object({
        running = optional(number)
        available = optional(number)
        desired_instances = optional(number)
        in_use = optional(number)
    }))
    fleet_type = optional(string)
    idle_disconnect_timeout_in_seconds = optional(number)
    instance_type = optional(string)
    name = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_appstream_fleet" "this" {
  compute_capacity = var.values.compute_capacity
  fleet_type = var.values.fleet_type
  idle_disconnect_timeout_in_seconds = var.values.idle_disconnect_timeout_in_seconds
  instance_type = var.values.instance_type
  name = var.values.name
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appstream_fleet.this.arn
}

output "created_time" {
    value = aws_appstream_fleet.this.created_time
}

output "description" {
    value = aws_appstream_fleet.this.description
}

output "disconnect_timeout_in_seconds" {
    value = aws_appstream_fleet.this.disconnect_timeout_in_seconds
}

output "display_name" {
    value = aws_appstream_fleet.this.display_name
}

output "fleet_type" {
    value = aws_appstream_fleet.this.fleet_type
}

output "iam_role_arn" {
    value = aws_appstream_fleet.this.iam_role_arn
}

output "image_arn" {
    value = aws_appstream_fleet.this.image_arn
}

output "image_name" {
    value = aws_appstream_fleet.this.image_name
}

output "max_user_duration_in_seconds" {
    value = aws_appstream_fleet.this.max_user_duration_in_seconds
}

output "state" {
    value = aws_appstream_fleet.this.state
}

output "stream_view" {
    value = aws_appstream_fleet.this.stream_view
}

