
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3_bucket_public_access_block
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    block_public_acls = optional(bool)
    block_public_policy = optional(bool)
    bucket = optional(string)
    ignore_public_acls = optional(bool)
    restrict_public_buckets = optional(bool)
  })
}

resource "aws_s3_bucket_public_access_block" "this" {
  block_public_acls = var.values.block_public_acls
  block_public_policy = var.values.block_public_policy
  bucket = var.values.bucket
  ignore_public_acls = var.values.ignore_public_acls
  restrict_public_buckets = var.values.restrict_public_buckets
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


