######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_applicationinsights_application
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    auto_config_enabled = optional(bool)
    auto_create = optional(bool)
    cwe_monitor_enabled = optional(bool)
    grouping_type = optional(string)
    ops_center_enabled = optional(bool)
    ops_item_sns_topic_arn = optional(string)
    resource_group_name = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_applicationinsights_application" "this" {

  {{- if $.Values.auto_config_enabled }}
  auto_config_enabled = var.values.auto_config_enabled
  {{- end }}
  {{- if $.Values.auto_create }}
  auto_create = var.values.auto_create
  {{- end }}
  {{- if $.Values.cwe_monitor_enabled }}
  cwe_monitor_enabled = var.values.cwe_monitor_enabled
  {{- end }}
  {{- if $.Values.grouping_type }}
  grouping_type = var.values.grouping_type
  {{- end }}
  {{- if $.Values.ops_center_enabled }}
  ops_center_enabled = var.values.ops_center_enabled
  {{- end }}
  {{- if $.Values.ops_item_sns_topic_arn }}
  ops_item_sns_topic_arn = var.values.ops_item_sns_topic_arn
  {{- end }}
  {{- if $.Values.resource_group_name }}
  resource_group_name = var.values.resource_group_name
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_applicationinsights_application.this.arn
}

output "ops_item_sns_topic_arn" {
    value = aws_applicationinsights_application.this.ops_item_sns_topic_arn
}

