######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3outposts_endpoint
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    outpost_id = optional(string)
    security_group_id = optional(string)
    subnet_id = optional(string)
  })
}

resource "aws_s3outposts_endpoint" "this" {

  {{- if $.Values.outpost_id }}
  outpost_id = var.values.outpost_id
  {{- end }}
  {{- if $.Values.security_group_id }}
  security_group_id = var.values.security_group_id
  {{- end }}
  {{- if $.Values.subnet_id }}
  subnet_id = var.values.subnet_id
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_s3outposts_endpoint.this.arn
}

output "cidr_block" {
    value = aws_s3outposts_endpoint.this.cidr_block
}

output "creation_time" {
    value = aws_s3outposts_endpoint.this.creation_time
}

