######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_docdb_cluster
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    availability_zones = optional(set(string))
    backup_retention_period = optional(number)
    cluster_identifier = optional(string)
    cluster_identifier_prefix = optional(string)
    db_subnet_group_name = optional(string)
    deletion_protection = optional(bool)
    enabled_cloudwatch_logs_exports = optional(list(string))
    engine = optional(string)
    final_snapshot_identifier = optional(string)
    global_cluster_identifier = optional(string)
    kms_key_id = optional(string)
    master_password = optional(string)
    master_username = optional(string)
    port = optional(number)
    skip_final_snapshot = optional(bool)
    snapshot_identifier = optional(string)
    storage_encrypted = optional(bool)
    tags = optional(map(string))
  })
}

resource "aws_docdb_cluster" "this" {

  {{- if $.Values.availability_zones }}
  availability_zones = var.values.availability_zones
  {{- end }}
  {{- if $.Values.backup_retention_period }}
  backup_retention_period = var.values.backup_retention_period
  {{- end }}
  {{- if $.Values.cluster_identifier }}
  cluster_identifier = var.values.cluster_identifier
  {{- end }}
  {{- if $.Values.cluster_identifier_prefix }}
  cluster_identifier_prefix = var.values.cluster_identifier_prefix
  {{- end }}
  {{- if $.Values.db_subnet_group_name }}
  db_subnet_group_name = var.values.db_subnet_group_name
  {{- end }}
  {{- if $.Values.deletion_protection }}
  deletion_protection = var.values.deletion_protection
  {{- end }}
  {{- if $.Values.enabled_cloudwatch_logs_exports }}
  enabled_cloudwatch_logs_exports = var.values.enabled_cloudwatch_logs_exports
  {{- end }}
  {{- if $.Values.engine }}
  engine = var.values.engine
  {{- end }}
  {{- if $.Values.final_snapshot_identifier }}
  final_snapshot_identifier = var.values.final_snapshot_identifier
  {{- end }}
  {{- if $.Values.global_cluster_identifier }}
  global_cluster_identifier = var.values.global_cluster_identifier
  {{- end }}
  {{- if $.Values.kms_key_id }}
  kms_key_id = var.values.kms_key_id
  {{- end }}
  {{- if $.Values.master_password }}
  master_password = var.values.master_password
  {{- end }}
  {{- if $.Values.master_username }}
  master_username = var.values.master_username
  {{- end }}
  {{- if $.Values.port }}
  port = var.values.port
  {{- end }}
  {{- if $.Values.skip_final_snapshot }}
  skip_final_snapshot = var.values.skip_final_snapshot
  {{- end }}
  {{- if $.Values.snapshot_identifier }}
  snapshot_identifier = var.values.snapshot_identifier
  {{- end }}
  {{- if $.Values.storage_encrypted }}
  storage_encrypted = var.values.storage_encrypted
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_docdb_cluster.this.arn
}

output "cluster_identifier" {
    value = aws_docdb_cluster.this.cluster_identifier
}

output "cluster_resource_id" {
    value = aws_docdb_cluster.this.cluster_resource_id
}

output "db_cluster_parameter_group_name" {
    value = aws_docdb_cluster.this.db_cluster_parameter_group_name
}

output "db_subnet_group_name" {
    value = aws_docdb_cluster.this.db_subnet_group_name
}

output "endpoint" {
    value = aws_docdb_cluster.this.endpoint
}

output "engine_version" {
    value = aws_docdb_cluster.this.engine_version
}

output "hosted_zone_id" {
    value = aws_docdb_cluster.this.hosted_zone_id
}

output "kms_key_id" {
    value = aws_docdb_cluster.this.kms_key_id
}

output "master_username" {
    value = aws_docdb_cluster.this.master_username
}

output "preferred_backup_window" {
    value = aws_docdb_cluster.this.preferred_backup_window
}

output "preferred_maintenance_window" {
    value = aws_docdb_cluster.this.preferred_maintenance_window
}

output "reader_endpoint" {
    value = aws_docdb_cluster.this.reader_endpoint
}

