
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_group_policy
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.32.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    group = string
    name = string
    name_prefix = string
    policy = string
  })
}

resource "aws_iam_group_policy" "default_resource" {
  group = var.values.group
  name = var.values.name
  name_prefix = var.values.name_prefix
  policy = var.values.policy
}
