
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_network_insights_path
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    destination = optional(string)
    destination_ip = optional(string)
    destination_port = optional(number)
    protocol = optional(string)
    source = optional(string)
    source_ip = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_ec2_network_insights_path" "this" {
  destination = var.values.destination
  destination_ip = var.values.destination_ip
  destination_port = var.values.destination_port
  protocol = var.values.protocol
  source = var.values.source
  source_ip = var.values.source_ip
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_network_insights_path.this.arn
}

