
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_user
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.32.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    force_destroy = bool
    name = string
    path = string
    permissions_boundary = string
    tags = map(string)
  })
}

resource "aws_iam_user" "default_resource" {
  force_destroy = var.values.force_destroy
  name = var.values.name
  path = var.values.path
  permissions_boundary = var.values.permissions_boundary
  tags = var.values.tags
}
