######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_role
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    assume_role_policy = optional(string)
    description = optional(string)
    force_detach_policies = optional(bool)
    max_session_duration = optional(number)
    name = optional(string)
    name_prefix = optional(string)
    path = optional(string)
    permissions_boundary = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_iam_role" "this" {

  {{- if $.Values.assume_role_policy }}
  assume_role_policy = var.values.assume_role_policy
  {{- end }}
  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}
  {{- if $.Values.force_detach_policies }}
  force_detach_policies = var.values.force_detach_policies
  {{- end }}
  {{- if $.Values.max_session_duration }}
  max_session_duration = var.values.max_session_duration
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.name_prefix }}
  name_prefix = var.values.name_prefix
  {{- end }}
  {{- if $.Values.path }}
  path = var.values.path
  {{- end }}
  {{- if $.Values.permissions_boundary }}
  permissions_boundary = var.values.permissions_boundary
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_iam_role.this.arn
}

output "create_date" {
    value = aws_iam_role.this.create_date
}

output "name" {
    value = aws_iam_role.this.name
}

output "unique_id" {
    value = aws_iam_role.this.unique_id
}

