
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_group_membership
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.32.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    group = string
    name = string
    users = set(string)
  })
}

resource "aws_iam_group_membership" "default_resource" {
  group = var.values.group
  name = var.values.name
  users = var.values.users
}
