######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3_account_public_access_block
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    account_id = optional(string)
    block_public_acls = optional(bool)
    block_public_policy = optional(bool)
    ignore_public_acls = optional(bool)
    restrict_public_buckets = optional(bool)
  })
}

resource "aws_s3_account_public_access_block" "this" {

  {{- if $.Values.account_id }}
  account_id = var.values.account_id
  {{- end }}
  {{- if $.Values.block_public_acls }}
  block_public_acls = var.values.block_public_acls
  {{- end }}
  {{- if $.Values.block_public_policy }}
  block_public_policy = var.values.block_public_policy
  {{- end }}
  {{- if $.Values.ignore_public_acls }}
  ignore_public_acls = var.values.ignore_public_acls
  {{- end }}
  {{- if $.Values.restrict_public_buckets }}
  restrict_public_buckets = var.values.restrict_public_buckets
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "account_id" {
    value = aws_s3_account_public_access_block.this.account_id
}

