######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appmesh_virtual_gateway
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    mesh_name = optional(string)
    mesh_owner = optional(string)
    name = optional(string)
    spec = optional(list(object({
        logging = optional(list(object({
            access_log = optional(list(object({
                file = optional(list(object({
                    path = optional(string)
                })))
            })))
        })))
        backend_defaults = optional(list(object({
            client_policy = optional(list(object({
                tls = optional(list(object({
                    validation = optional(list(object({
                        subject_alternative_names = optional(list(object({
                            match = optional(list(object({
                                exact = optional(set(string))
                            })))
                        })))
                        trust = optional(list(object({
                            acm = optional(list(object({
                                certificate_authority_arns = optional(set(string))
                            })))
                            file = optional(list(object({
                                certificate_chain = optional(string)
                            })))
                            sds = optional(list(object({
                                secret_name = optional(string)
                            })))
                        })))
                    })))
                    certificate = optional(list(object({
                        sds = optional(list(object({
                            secret_name = optional(string)
                        })))
                        file = optional(list(object({
                            certificate_chain = optional(string)
                            private_key = optional(string)
                        })))
                    })))
                    enforce = optional(bool)
                    ports = optional(set(number))
                })))
            })))
        })))
        listener = optional(list(object({
            connection_pool = optional(list(object({
                grpc = optional(list(object({
                    max_requests = optional(number)
                })))
                http = optional(list(object({
                    max_connections = optional(number)
                    max_pending_requests = optional(number)
                })))
                http2 = optional(list(object({
                    max_requests = optional(number)
                })))
            })))
            health_check = optional(list(object({
                port = optional(number)
                protocol = optional(string)
                timeout_millis = optional(number)
                unhealthy_threshold = optional(number)
                healthy_threshold = optional(number)
                interval_millis = optional(number)
                path = optional(string)
            })))
            port_mapping = optional(list(object({
                port = optional(number)
                protocol = optional(string)
            })))
            tls = optional(list(object({
                certificate = optional(list(object({
                    acm = optional(list(object({
                        certificate_arn = optional(string)
                    })))
                    file = optional(list(object({
                        certificate_chain = optional(string)
                        private_key = optional(string)
                    })))
                    sds = optional(list(object({
                        secret_name = optional(string)
                    })))
                })))
                mode = optional(string)
                validation = optional(list(object({
                    subject_alternative_names = optional(list(object({
                        match = optional(list(object({
                            exact = optional(set(string))
                        })))
                    })))
                    trust = optional(list(object({
                        sds = optional(list(object({
                            secret_name = optional(string)
                        })))
                        file = optional(list(object({
                            certificate_chain = optional(string)
                        })))
                    })))
                })))
            })))
        })))
    })))
    tags = optional(map(string))
  })
}

resource "aws_appmesh_virtual_gateway" "this" {

  {{- if $.Values.mesh_name }}
  mesh_name = var.values.mesh_name
  {{- end }}
  {{- if $.Values.mesh_owner }}
  mesh_owner = var.values.mesh_owner
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.spec }}
  spec = var.values.spec
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appmesh_virtual_gateway.this.arn
}

output "created_date" {
    value = aws_appmesh_virtual_gateway.this.created_date
}

output "last_updated_date" {
    value = aws_appmesh_virtual_gateway.this.last_updated_date
}

output "mesh_owner" {
    value = aws_appmesh_virtual_gateway.this.mesh_owner
}

output "resource_owner" {
    value = aws_appmesh_virtual_gateway.this.resource_owner
}

