######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_transit_gateway_connect_peer
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    bgp_asn = optional(string)
    inside_cidr_blocks = optional(set(string))
    peer_address = optional(string)
    tags = optional(map(string))
    transit_gateway_address = optional(string)
    transit_gateway_attachment_id = optional(string)
  })
}

resource "aws_ec2_transit_gateway_connect_peer" "this" {

  {{- if $.Values.bgp_asn }}
  bgp_asn = var.values.bgp_asn
  {{- end }}
  {{- if $.Values.inside_cidr_blocks }}
  inside_cidr_blocks = var.values.inside_cidr_blocks
  {{- end }}
  {{- if $.Values.peer_address }}
  peer_address = var.values.peer_address
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}
  {{- if $.Values.transit_gateway_address }}
  transit_gateway_address = var.values.transit_gateway_address
  {{- end }}
  {{- if $.Values.transit_gateway_attachment_id }}
  transit_gateway_attachment_id = var.values.transit_gateway_attachment_id
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_transit_gateway_connect_peer.this.arn
}

output "bgp_asn" {
    value = aws_ec2_transit_gateway_connect_peer.this.bgp_asn
}

output "transit_gateway_address" {
    value = aws_ec2_transit_gateway_connect_peer.this.transit_gateway_address
}

