######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3_bucket_inventory
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    bucket = optional(string)
    destination = optional(list({
        bucket = optional(list({
            account_id = optional(string)
            prefix = optional(string)
            encryption = optional(list({
                sse_kms = optional(list({
                    key_id = optional(string)
                }))
                sse_s3 = optional(list({
                }))
            }))
            format = optional(string)
            bucket_arn = optional(string)
        }))
    }))
    enabled = optional(bool)
    filter = optional(list({
        prefix = optional(string)
    }))
    included_object_versions = optional(string)
    name = optional(string)
    optional_fields = optional(set(string))
    schedule = optional(list({
        frequency = optional(string)
    }))
  })
}

resource "aws_s3_bucket_inventory" "this" {

  {{- if $.Values.bucket }}
  bucket = var.values.bucket
  {{- end }}
  {{- if $.Values.destination }}
  destination = var.values.destination
  {{- end }}
  {{- if $.Values.enabled }}
  enabled = var.values.enabled
  {{- end }}
  {{- if $.Values.filter }}
  filter = var.values.filter
  {{- end }}
  {{- if $.Values.included_object_versions }}
  included_object_versions = var.values.included_object_versions
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.optional_fields }}
  optional_fields = var.values.optional_fields
  {{- end }}
  {{- if $.Values.schedule }}
  schedule = var.values.schedule
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


