
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appautoscaling_scheduled_action
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    end_time = optional(string)
    name = optional(string)
    resource_id = optional(string)
    scalable_dimension = optional(string)
    scalable_target_action = optional(object({
        min_capacity = optional(string)
        max_capacity = optional(string)
    }))
    schedule = optional(string)
    service_namespace = optional(string)
    start_time = optional(string)
    timezone = optional(string)
  })
}

resource "aws_appautoscaling_scheduled_action" "this" {
  end_time = var.values.end_time
  name = var.values.name
  resource_id = var.values.resource_id
  scalable_dimension = var.values.scalable_dimension
  scalable_target_action = var.values.scalable_target_action
  schedule = var.values.schedule
  service_namespace = var.values.service_namespace
  start_time = var.values.start_time
  timezone = var.values.timezone
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appautoscaling_scheduled_action.this.arn
}

