######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appautoscaling_scheduled_action
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    end_time = optional(string)
    name = optional(string)
    resource_id = optional(string)
    scalable_dimension = optional(string)
    scalable_target_action = optional(list(object({
        max_capacity = optional(string)
        min_capacity = optional(string)
    })))
    schedule = optional(string)
    service_namespace = optional(string)
    start_time = optional(string)
    timezone = optional(string)
  })
}

resource "aws_appautoscaling_scheduled_action" "this" {

  {{- if $.Values.end_time }}
  end_time = var.values.end_time
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.resource_id }}
  resource_id = var.values.resource_id
  {{- end }}
  {{- if $.Values.scalable_dimension }}
  scalable_dimension = var.values.scalable_dimension
  {{- end }}
  {{- if $.Values.scalable_target_action }}
  dynamic "scalable_target_action" {
    for_each = var.values.scalable_target_action[*]
    content {
      max_capacity = scalable_target_action.value.max_capacity
      min_capacity = scalable_target_action.value.min_capacity
    }
  }
  {{- end }}
  {{- if $.Values.schedule }}
  schedule = var.values.schedule
  {{- end }}
  {{- if $.Values.service_namespace }}
  service_namespace = var.values.service_namespace
  {{- end }}
  {{- if $.Values.start_time }}
  start_time = var.values.start_time
  {{- end }}
  {{- if $.Values.timezone }}
  timezone = var.values.timezone
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appautoscaling_scheduled_action.this.arn
}

