######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3control_object_lambda_access_point
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    account_id = optional(string)
    configuration = optional(list(object({
        transformation_configuration = optional(set(object({
            content_transformation = optional(list(object({
                aws_lambda = optional(list(object({
                    function_arn = optional(string)
                    function_payload = optional(string)
                })))
            })))
            actions = optional(set(string))
        })))
        allowed_features = optional(set(string))
        cloud_watch_metrics_enabled = optional(bool)
        supporting_access_point = optional(string)
    })))
    name = optional(string)
  })
}

resource "aws_s3control_object_lambda_access_point" "this" {

  {{- if $.Values.account_id }}
  account_id = var.values.account_id
  {{- end }}
  {{- if $.Values.configuration }}
  dynamic "configuration" {
    for_each = var.values.configuration[*]
    content {
      allowed_features = configuration.value.allowed_features
      cloud_watch_metrics_enabled = configuration.value.cloud_watch_metrics_enabled
      supporting_access_point = configuration.value.supporting_access_point
      dynamic "transformation_configuration" {
        for_each = configuration.value.transformation_configuration[*]
        content {
          dynamic "content_transformation" {
            for_each = transformation_configuration.value.content_transformation[*]
            content {
              dynamic "aws_lambda" {
                for_each = content_transformation.value.aws_lambda[*]
                content {
                  function_arn = aws_lambda.value.function_arn
                  function_payload = aws_lambda.value.function_payload
                }
              }
            }
          }
          actions = transformation_configuration.value.actions
        }
      }
    }
  }
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "account_id" {
    value = aws_s3control_object_lambda_access_point.this.account_id
}

output "arn" {
    value = aws_s3control_object_lambda_access_point.this.arn
}

