
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_docdb_cluster_parameter_group
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    description = optional(string)
    family = optional(string)
    name = optional(string)
    name_prefix = optional(string)
    parameter = optional(set(any))
    tags = optional(map(string))
  })
}

resource "aws_docdb_cluster_parameter_group" "this" {
  description = var.values.description
  family = var.values.family
  name = var.values.name
  name_prefix = var.values.name_prefix
  parameter = var.values.parameter
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_docdb_cluster_parameter_group.this.arn
}

output "name" {
    value = aws_docdb_cluster_parameter_group.this.name
}

