######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appconfig_hosted_configuration_version
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    application_id = optional(string)
    configuration_profile_id = optional(string)
    content = optional(string)
    content_type = optional(string)
    description = optional(string)
  })
}

resource "aws_appconfig_hosted_configuration_version" "this" {

  {{- if $.Values.application_id }}
  application_id = var.values.application_id
  {{- end }}
  {{- if $.Values.configuration_profile_id }}
  configuration_profile_id = var.values.configuration_profile_id
  {{- end }}
  {{- if $.Values.content }}
  content = var.values.content
  {{- end }}
  {{- if $.Values.content_type }}
  content_type = var.values.content_type
  {{- end }}
  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appconfig_hosted_configuration_version.this.arn
}

output "version_number" {
    value = aws_appconfig_hosted_configuration_version.this.version_number
}

