
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_transit_gateway_peering_attachment
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    peer_account_id = optional(string)
    peer_region = optional(string)
    peer_transit_gateway_id = optional(string)
    tags = optional(map(string))
    transit_gateway_id = optional(string)
  })
}

resource "aws_ec2_transit_gateway_peering_attachment" "this" {
  peer_account_id = var.values.peer_account_id
  peer_region = var.values.peer_region
  peer_transit_gateway_id = var.values.peer_transit_gateway_id
  tags = var.values.tags
  transit_gateway_id = var.values.transit_gateway_id
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "peer_account_id" {
    value = aws_ec2_transit_gateway_peering_attachment.this.peer_account_id
}

