
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_service_specific_credential
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.32.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    service_name = optional(string)
    status = optional(string)
    user_name = optional(string)
  })
}

resource "aws_iam_service_specific_credential" "default_resource" {
  service_name = var.values.service_name
  status = var.values.status
  user_name = var.values.user_name
}
