######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_docdb_cluster_instance
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    auto_minor_version_upgrade = optional(bool)
    availability_zone = optional(string)
    cluster_identifier = optional(string)
    engine = optional(string)
    identifier = optional(string)
    identifier_prefix = optional(string)
    instance_class = optional(string)
    promotion_tier = optional(number)
    tags = optional(map(string))
  })
}

resource "aws_docdb_cluster_instance" "this" {

  {{- if $.Values.auto_minor_version_upgrade }}
  auto_minor_version_upgrade = var.values.auto_minor_version_upgrade
  {{- end }}
  {{- if $.Values.availability_zone }}
  availability_zone = var.values.availability_zone
  {{- end }}
  {{- if $.Values.cluster_identifier }}
  cluster_identifier = var.values.cluster_identifier
  {{- end }}
  {{- if $.Values.engine }}
  engine = var.values.engine
  {{- end }}
  {{- if $.Values.identifier }}
  identifier = var.values.identifier
  {{- end }}
  {{- if $.Values.identifier_prefix }}
  identifier_prefix = var.values.identifier_prefix
  {{- end }}
  {{- if $.Values.instance_class }}
  instance_class = var.values.instance_class
  {{- end }}
  {{- if $.Values.promotion_tier }}
  promotion_tier = var.values.promotion_tier
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_docdb_cluster_instance.this.arn
}

output "availability_zone" {
    value = aws_docdb_cluster_instance.this.availability_zone
}

output "ca_cert_identifier" {
    value = aws_docdb_cluster_instance.this.ca_cert_identifier
}

output "db_subnet_group_name" {
    value = aws_docdb_cluster_instance.this.db_subnet_group_name
}

output "dbi_resource_id" {
    value = aws_docdb_cluster_instance.this.dbi_resource_id
}

output "endpoint" {
    value = aws_docdb_cluster_instance.this.endpoint
}

output "engine_version" {
    value = aws_docdb_cluster_instance.this.engine_version
}

output "identifier" {
    value = aws_docdb_cluster_instance.this.identifier
}

output "kms_key_id" {
    value = aws_docdb_cluster_instance.this.kms_key_id
}

output "port" {
    value = aws_docdb_cluster_instance.this.port
}

output "preferred_backup_window" {
    value = aws_docdb_cluster_instance.this.preferred_backup_window
}

output "preferred_maintenance_window" {
    value = aws_docdb_cluster_instance.this.preferred_maintenance_window
}

