######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_subnet_cidr_reservation
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    cidr_block = optional(string)
    description = optional(string)
    reservation_type = optional(string)
    subnet_id = optional(string)
  })
}

resource "aws_ec2_subnet_cidr_reservation" "this" {

  {{- if $.Values.cidr_block }}
  cidr_block = var.values.cidr_block
  {{- end }}
  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}
  {{- if $.Values.reservation_type }}
  reservation_type = var.values.reservation_type
  {{- end }}
  {{- if $.Values.subnet_id }}
  subnet_id = var.values.subnet_id
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "owner_id" {
    value = aws_ec2_subnet_cidr_reservation.this.owner_id
}

