
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_openid_connect_provider
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.32.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    client_id_list = optional(list(string))
    tags = optional(map(string))
    thumbprint_list = optional(list(string))
    url = optional(string)
  })
}

resource "aws_iam_openid_connect_provider" "default_resource" {
  client_id_list = var.values.client_id_list
  tags = var.values.tags
  thumbprint_list = var.values.thumbprint_list
  url = var.values.url
}
