######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_client_vpn_endpoint
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    authentication_options = optional(list(object({
        saml_provider_arn = optional(string)
        self_service_saml_provider_arn = optional(string)
        type = optional(string)
        active_directory_id = optional(string)
        root_certificate_chain_arn = optional(string)
    })))
    client_cidr_block = optional(string)
    connection_log_options = optional(list(object({
        enabled = optional(bool)
        cloudwatch_log_group = optional(string)
        cloudwatch_log_stream = optional(string)
    })))
    description = optional(string)
    dns_servers = optional(list(string))
    self_service_portal = optional(string)
    server_certificate_arn = optional(string)
    session_timeout_hours = optional(number)
    split_tunnel = optional(bool)
    tags = optional(map(string))
    transport_protocol = optional(string)
    vpn_port = optional(number)
  })
}

resource "aws_ec2_client_vpn_endpoint" "this" {

  {{- if $.Values.authentication_options }}
  dynamic "authentication_options" {
    for_each = var.values.authentication_options[*]
    content {
      active_directory_id = authentication_options.value.active_directory_id
      root_certificate_chain_arn = authentication_options.value.root_certificate_chain_arn
      saml_provider_arn = authentication_options.value.saml_provider_arn
      self_service_saml_provider_arn = authentication_options.value.self_service_saml_provider_arn
      type = authentication_options.value.type
    }
  }
  {{- end }}
  {{- if $.Values.client_cidr_block }}
  client_cidr_block = var.values.client_cidr_block
  {{- end }}
  {{- if $.Values.connection_log_options }}
  dynamic "connection_log_options" {
    for_each = var.values.connection_log_options[*]
    content {
      cloudwatch_log_group = connection_log_options.value.cloudwatch_log_group
      cloudwatch_log_stream = connection_log_options.value.cloudwatch_log_stream
      enabled = connection_log_options.value.enabled
    }
  }
  {{- end }}
  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}
  {{- if $.Values.dns_servers }}
  dns_servers = var.values.dns_servers
  {{- end }}
  {{- if $.Values.self_service_portal }}
  self_service_portal = var.values.self_service_portal
  {{- end }}
  {{- if $.Values.server_certificate_arn }}
  server_certificate_arn = var.values.server_certificate_arn
  {{- end }}
  {{- if $.Values.session_timeout_hours }}
  session_timeout_hours = var.values.session_timeout_hours
  {{- end }}
  {{- if $.Values.split_tunnel }}
  split_tunnel = var.values.split_tunnel
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}
  {{- if $.Values.transport_protocol }}
  transport_protocol = var.values.transport_protocol
  {{- end }}
  {{- if $.Values.vpn_port }}
  vpn_port = var.values.vpn_port
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_client_vpn_endpoint.this.arn
}

output "dns_name" {
    value = aws_ec2_client_vpn_endpoint.this.dns_name
}

output "server_certificate_arn" {
    value = aws_ec2_client_vpn_endpoint.this.server_certificate_arn
}

output "status" {
    value = aws_ec2_client_vpn_endpoint.this.status
}

output "vpc_id" {
    value = aws_ec2_client_vpn_endpoint.this.vpc_id
}

