
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_traffic_mirror_filter_rule
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    description = optional(string)
    destination_cidr_block = optional(string)
    destination_port_range = optional(object({
        to_port = optional(number)
        from_port = optional(number)
    }))
    protocol = optional(number)
    rule_action = optional(string)
    rule_number = optional(number)
    source_cidr_block = optional(string)
    source_port_range = optional(object({
        from_port = optional(number)
        to_port = optional(number)
    }))
    traffic_direction = optional(string)
    traffic_mirror_filter_id = optional(string)
  })
}

resource "aws_ec2_traffic_mirror_filter_rule" "this" {
  description = var.values.description
  destination_cidr_block = var.values.destination_cidr_block
  destination_port_range = var.values.destination_port_range
  protocol = var.values.protocol
  rule_action = var.values.rule_action
  rule_number = var.values.rule_number
  source_cidr_block = var.values.source_cidr_block
  source_port_range = var.values.source_port_range
  traffic_direction = var.values.traffic_direction
  traffic_mirror_filter_id = var.values.traffic_mirror_filter_id
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_traffic_mirror_filter_rule.this.arn
}

