######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appflow_connector_profile
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    connection_mode = optional(string)
    connector_label = optional(string)
    connector_profile_config = optional(list({
        connector_profile_credentials = optional(list({
            trendmicro = optional(list({
                api_secret_key = optional(string)
            }))
            zendesk = optional(list({
                access_token = optional(string)
                client_id = optional(string)
                client_secret = optional(string)
                oauth_request = optional(list({
                    auth_code = optional(string)
                    redirect_uri = optional(string)
                }))
            }))
            datadog = optional(list({
                api_key = optional(string)
                application_key = optional(string)
            }))
            infor_nexus = optional(list({
                secret_access_key = optional(string)
                user_id = optional(string)
                access_key_id = optional(string)
                datakey = optional(string)
            }))
            marketo = optional(list({
                client_secret = optional(string)
                oauth_request = optional(list({
                    auth_code = optional(string)
                    redirect_uri = optional(string)
                }))
                access_token = optional(string)
                client_id = optional(string)
            }))
            redshift = optional(list({
                username = optional(string)
                password = optional(string)
            }))
            service_now = optional(list({
                password = optional(string)
                username = optional(string)
            }))
            sapo_data = optional(list({
                basic_auth_credentials = optional(list({
                    password = optional(string)
                    username = optional(string)
                }))
                oauth_credentials = optional(list({
                    access_token = optional(string)
                    client_id = optional(string)
                    client_secret = optional(string)
                    oauth_request = optional(list({
                        auth_code = optional(string)
                        redirect_uri = optional(string)
                    }))
                    refresh_token = optional(string)
                }))
            }))
            veeva = optional(list({
                password = optional(string)
                username = optional(string)
            }))
            amplitude = optional(list({
                api_key = optional(string)
                secret_key = optional(string)
            }))
            custom_connector = optional(list({
                oauth2 = optional(list({
                    access_token = optional(string)
                    client_id = optional(string)
                    client_secret = optional(string)
                    oauth_request = optional(list({
                        redirect_uri = optional(string)
                        auth_code = optional(string)
                    }))
                    refresh_token = optional(string)
                }))
                api_key = optional(list({
                    api_key = optional(string)
                    api_secret_key = optional(string)
                }))
                authentication_type = optional(string)
                basic = optional(list({
                    password = optional(string)
                    username = optional(string)
                }))
                custom = optional(list({
                    credentials_map = optional(map(string))
                    custom_authentication_type = optional(string)
                }))
            }))
            dynatrace = optional(list({
                api_token = optional(string)
            }))
            google_analytics = optional(list({
                access_token = optional(string)
                client_id = optional(string)
                client_secret = optional(string)
                oauth_request = optional(list({
                    auth_code = optional(string)
                    redirect_uri = optional(string)
                }))
                refresh_token = optional(string)
            }))
            salesforce = optional(list({
                access_token = optional(string)
                client_credentials_arn = optional(string)
                oauth_request = optional(list({
                    auth_code = optional(string)
                    redirect_uri = optional(string)
                }))
                refresh_token = optional(string)
            }))
            honeycode = optional(list({
                access_token = optional(string)
                oauth_request = optional(list({
                    auth_code = optional(string)
                    redirect_uri = optional(string)
                }))
                refresh_token = optional(string)
            }))
            singular = optional(list({
                api_key = optional(string)
            }))
            slack = optional(list({
                access_token = optional(string)
                client_id = optional(string)
                client_secret = optional(string)
                oauth_request = optional(list({
                    redirect_uri = optional(string)
                    auth_code = optional(string)
                }))
            }))
            snowflake = optional(list({
                password = optional(string)
                username = optional(string)
            }))
        }))
        connector_profile_properties = optional(list({
            service_now = optional(list({
                instance_url = optional(string)
            }))
            singular = optional(list({
            }))
            honeycode = optional(list({
            }))
            redshift = optional(list({
                bucket_name = optional(string)
                bucket_prefix = optional(string)
                database_url = optional(string)
                role_arn = optional(string)
            }))
            salesforce = optional(list({
                instance_url = optional(string)
                is_sandbox_environment = optional(bool)
            }))
            snowflake = optional(list({
                region = optional(string)
                stage = optional(string)
                warehouse = optional(string)
                account_name = optional(string)
                bucket_name = optional(string)
                bucket_prefix = optional(string)
                private_link_service_name = optional(string)
            }))
            amplitude = optional(list({
            }))
            marketo = optional(list({
                instance_url = optional(string)
            }))
            infor_nexus = optional(list({
                instance_url = optional(string)
            }))
            sapo_data = optional(list({
                port_number = optional(number)
                private_link_service_name = optional(string)
                application_host_url = optional(string)
                application_service_path = optional(string)
                client_number = optional(string)
                logon_language = optional(string)
                oauth_properties = optional(list({
                    auth_code_url = optional(string)
                    oauth_scopes = optional(list(string))
                    token_url = optional(string)
                }))
            }))
            veeva = optional(list({
                instance_url = optional(string)
            }))
            custom_connector = optional(list({
                oauth2_properties = optional(list({
                    oauth2_grant_type = optional(string)
                    token_url = optional(string)
                    token_url_custom_properties = optional(map(string))
                }))
                profile_properties = optional(map(string))
            }))
            dynatrace = optional(list({
                instance_url = optional(string)
            }))
            slack = optional(list({
                instance_url = optional(string)
            }))
            trendmicro = optional(list({
            }))
            zendesk = optional(list({
                instance_url = optional(string)
            }))
            datadog = optional(list({
                instance_url = optional(string)
            }))
            google_analytics = optional(list({
            }))
        }))
    }))
    connector_type = optional(string)
    kms_arn = optional(string)
    name = optional(string)
  })
}

resource "aws_appflow_connector_profile" "this" {

  {{- if $.Values.connection_mode }}
  connection_mode = var.values.connection_mode
  {{- end }}
  {{- if $.Values.connector_label }}
  connector_label = var.values.connector_label
  {{- end }}
  {{- if $.Values.connector_profile_config }}
  connector_profile_config = var.values.connector_profile_config
  {{- end }}
  {{- if $.Values.connector_type }}
  connector_type = var.values.connector_type
  {{- end }}
  {{- if $.Values.kms_arn }}
  kms_arn = var.values.kms_arn
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appflow_connector_profile.this.arn
}

output "credentials_arn" {
    value = aws_appflow_connector_profile.this.credentials_arn
}

output "kms_arn" {
    value = aws_appflow_connector_profile.this.kms_arn
}

