######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3_access_point
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    account_id = optional(string)
    bucket = optional(string)
    name = optional(string)
    public_access_block_configuration = optional(list({
        block_public_acls = optional(bool)
        block_public_policy = optional(bool)
        ignore_public_acls = optional(bool)
        restrict_public_buckets = optional(bool)
    }))
    vpc_configuration = optional(list({
        vpc_id = optional(string)
    }))
  })
}

resource "aws_s3_access_point" "this" {

  {{- if $.Values.account_id }}
  account_id = var.values.account_id
  {{- end }}
  {{- if $.Values.bucket }}
  bucket = var.values.bucket
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.public_access_block_configuration }}
  public_access_block_configuration = var.values.public_access_block_configuration
  {{- end }}
  {{- if $.Values.vpc_configuration }}
  vpc_configuration = var.values.vpc_configuration
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "account_id" {
    value = aws_s3_access_point.this.account_id
}

output "alias" {
    value = aws_s3_access_point.this.alias
}

output "arn" {
    value = aws_s3_access_point.this.arn
}

output "domain_name" {
    value = aws_s3_access_point.this.domain_name
}

output "network_origin" {
    value = aws_s3_access_point.this.network_origin
}

output "policy" {
    value = aws_s3_access_point.this.policy
}

