######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_traffic_mirror_target
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    description = optional(string)
    gateway_load_balancer_endpoint_id = optional(string)
    network_interface_id = optional(string)
    network_load_balancer_arn = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_ec2_traffic_mirror_target" "this" {

  {{- if $.Values.description }}
  description = var.values.description
  {{- end }}
  {{- if $.Values.gateway_load_balancer_endpoint_id }}
  gateway_load_balancer_endpoint_id = var.values.gateway_load_balancer_endpoint_id
  {{- end }}
  {{- if $.Values.network_interface_id }}
  network_interface_id = var.values.network_interface_id
  {{- end }}
  {{- if $.Values.network_load_balancer_arn }}
  network_load_balancer_arn = var.values.network_load_balancer_arn
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_traffic_mirror_target.this.arn
}

output "network_load_balancer_arn" {
    value = aws_ec2_traffic_mirror_target.this.network_load_balancer_arn
}

output "owner_id" {
    value = aws_ec2_traffic_mirror_target.this.owner_id
}

