######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_capacity_reservation
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    availability_zone = optional(string)
    ebs_optimized = optional(bool)
    end_date = optional(string)
    end_date_type = optional(string)
    ephemeral_storage = optional(bool)
    instance_count = optional(number)
    instance_match_criteria = optional(string)
    instance_platform = optional(string)
    instance_type = optional(string)
    outpost_arn = optional(string)
    placement_group_arn = optional(string)
    tags = optional(map(string))
    tenancy = optional(string)
  })
}

resource "aws_ec2_capacity_reservation" "this" {

  {{- if $.Values.availability_zone }}
  availability_zone = var.values.availability_zone
  {{- end }}
  {{- if $.Values.ebs_optimized }}
  ebs_optimized = var.values.ebs_optimized
  {{- end }}
  {{- if $.Values.end_date }}
  end_date = var.values.end_date
  {{- end }}
  {{- if $.Values.end_date_type }}
  end_date_type = var.values.end_date_type
  {{- end }}
  {{- if $.Values.ephemeral_storage }}
  ephemeral_storage = var.values.ephemeral_storage
  {{- end }}
  {{- if $.Values.instance_count }}
  instance_count = var.values.instance_count
  {{- end }}
  {{- if $.Values.instance_match_criteria }}
  instance_match_criteria = var.values.instance_match_criteria
  {{- end }}
  {{- if $.Values.instance_platform }}
  instance_platform = var.values.instance_platform
  {{- end }}
  {{- if $.Values.instance_type }}
  instance_type = var.values.instance_type
  {{- end }}
  {{- if $.Values.outpost_arn }}
  outpost_arn = var.values.outpost_arn
  {{- end }}
  {{- if $.Values.placement_group_arn }}
  placement_group_arn = var.values.placement_group_arn
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}
  {{- if $.Values.tenancy }}
  tenancy = var.values.tenancy
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_capacity_reservation.this.arn
}

output "outpost_arn" {
    value = aws_ec2_capacity_reservation.this.outpost_arn
}

output "owner_id" {
    value = aws_ec2_capacity_reservation.this.owner_id
}

output "placement_group_arn" {
    value = aws_ec2_capacity_reservation.this.placement_group_arn
}

