######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ecs_capacity_provider
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    auto_scaling_group_provider = optional(list(object({
        auto_scaling_group_arn = optional(string)
        managed_scaling = optional(list(object({
            minimum_scaling_step_size = optional(number)
            status = optional(string)
            target_capacity = optional(number)
            instance_warmup_period = optional(number)
            maximum_scaling_step_size = optional(number)
        })))
        managed_termination_protection = optional(string)
    })))
    name = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_ecs_capacity_provider" "this" {

  {{- if $.Values.auto_scaling_group_provider }}
  dynamic "auto_scaling_group_provider" {
    for_each = var.values.auto_scaling_group_provider[*]
    content {
      managed_termination_protection = auto_scaling_group_provider.value.managed_termination_protection
      auto_scaling_group_arn = auto_scaling_group_provider.value.auto_scaling_group_arn
      dynamic "managed_scaling" {
        for_each = auto_scaling_group_provider.value.managed_scaling[*]
        content {
          instance_warmup_period = managed_scaling.value.instance_warmup_period
          maximum_scaling_step_size = managed_scaling.value.maximum_scaling_step_size
          minimum_scaling_step_size = managed_scaling.value.minimum_scaling_step_size
          status = managed_scaling.value.status
          target_capacity = managed_scaling.value.target_capacity
        }
      }
    }
  }
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ecs_capacity_provider.this.arn
}

