
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ecrpublic_repository
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    catalog_data = optional(object({
        about_text = optional(string)
        architectures = optional(set(string))
        description = optional(string)
        logo_image_blob = optional(string)
        operating_systems = optional(set(string))
        usage_text = optional(string)
    }))
    force_destroy = optional(bool)
    repository_name = optional(string)
  })
}

resource "aws_ecrpublic_repository" "this" {
  catalog_data = var.values.catalog_data
  force_destroy = var.values.force_destroy
  repository_name = var.values.repository_name
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ecrpublic_repository.this.arn
}

output "registry_id" {
    value = aws_ecrpublic_repository.this.registry_id
}

output "repository_uri" {
    value = aws_ecrpublic_repository.this.repository_uri
}

