######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3_bucket_lifecycle_configuration
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    bucket = optional(string)
    expected_bucket_owner = optional(string)
    rule = optional(list(object({
        status = optional(string)
        transition = optional(set(object({
            date = optional(string)
            days = optional(number)
            storage_class = optional(string)
        })))
        abort_incomplete_multipart_upload = optional(list(object({
            days_after_initiation = optional(number)
        })))
        expiration = optional(list(object({
            expired_object_delete_marker = optional(bool)
            date = optional(string)
            days = optional(number)
        })))
        noncurrent_version_transition = optional(set(object({
            storage_class = optional(string)
            newer_noncurrent_versions = optional(string)
            noncurrent_days = optional(number)
        })))
        prefix = optional(string)
        filter = optional(list(object({
            and = optional(list(object({
                object_size_less_than = optional(number)
                prefix = optional(string)
                tags = optional(map(string))
                object_size_greater_than = optional(number)
            })))
            object_size_greater_than = optional(string)
            object_size_less_than = optional(string)
            prefix = optional(string)
            tag = optional(list(object({
                value = optional(string)
                key = optional(string)
            })))
        })))
        id = optional(string)
        noncurrent_version_expiration = optional(list(object({
            newer_noncurrent_versions = optional(string)
            noncurrent_days = optional(number)
        })))
    })))
  })
}

resource "aws_s3_bucket_lifecycle_configuration" "this" {

  {{- if $.Values.bucket }}
  bucket = var.values.bucket
  {{- end }}
  {{- if $.Values.expected_bucket_owner }}
  expected_bucket_owner = var.values.expected_bucket_owner
  {{- end }}
  {{- if $.Values.rule }}
  dynamic "rule" {
    for_each = var.values.rule[*]
    content {
      dynamic "filter" {
        for_each = rule.value.filter[*]
        content {
          prefix = filter.value.prefix
          dynamic "tag" {
            for_each = filter.value.tag[*]
            content {
              value = tag.value.value
              key = tag.value.key
            }
          }
          dynamic "and" {
            for_each = filter.value.and[*]
            content {
              object_size_greater_than = and.value.object_size_greater_than
              object_size_less_than = and.value.object_size_less_than
              prefix = and.value.prefix
              tags = and.value.tags
            }
          }
          object_size_greater_than = filter.value.object_size_greater_than
          object_size_less_than = filter.value.object_size_less_than
        }
      }
      id = rule.value.id
      dynamic "noncurrent_version_expiration" {
        for_each = rule.value.noncurrent_version_expiration[*]
        content {
          noncurrent_days = noncurrent_version_expiration.value.noncurrent_days
          newer_noncurrent_versions = noncurrent_version_expiration.value.newer_noncurrent_versions
        }
      }
      dynamic "abort_incomplete_multipart_upload" {
        for_each = rule.value.abort_incomplete_multipart_upload[*]
        content {
          days_after_initiation = abort_incomplete_multipart_upload.value.days_after_initiation
        }
      }
      dynamic "expiration" {
        for_each = rule.value.expiration[*]
        content {
          date = expiration.value.date
          days = expiration.value.days
          expired_object_delete_marker = expiration.value.expired_object_delete_marker
        }
      }
      dynamic "noncurrent_version_transition" {
        for_each = rule.value.noncurrent_version_transition[*]
        content {
          newer_noncurrent_versions = noncurrent_version_transition.value.newer_noncurrent_versions
          noncurrent_days = noncurrent_version_transition.value.noncurrent_days
          storage_class = noncurrent_version_transition.value.storage_class
        }
      }
      prefix = rule.value.prefix
      status = rule.value.status
      dynamic "transition" {
        for_each = rule.value.transition[*]
        content {
          date = transition.value.date
          days = transition.value.days
          storage_class = transition.value.storage_class
        }
      }
    }
  }
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


