
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_s3_bucket_lifecycle_configuration
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    bucket = optional(string)
    expected_bucket_owner = optional(string)
    rule = optional(object({
        noncurrent_version_transition = optional(set(any))
        prefix = optional(string)
        noncurrent_version_expiration = optional(object({
            newer_noncurrent_versions = optional(string)
            noncurrent_days = optional(number)
        }))
        status = optional(string)
        transition = optional(set(any))
        abort_incomplete_multipart_upload = optional(object({
            days_after_initiation = optional(number)
        }))
        expiration = optional(object({
            expired_object_delete_marker = optional(bool)
            date = optional(string)
            days = optional(number)
        }))
        filter = optional(object({
            and = optional(object({
                object_size_greater_than = optional(number)
                object_size_less_than = optional(number)
                prefix = optional(string)
                tags = optional(map(string))
            }))
            object_size_greater_than = optional(string)
            object_size_less_than = optional(string)
            prefix = optional(string)
            tag = optional(object({
                key = optional(string)
                value = optional(string)
            }))
        }))
        id = optional(string)
    }))
  })
}

resource "aws_s3_bucket_lifecycle_configuration" "this" {
  bucket = var.values.bucket
  expected_bucket_owner = var.values.expected_bucket_owner
  rule = var.values.rule
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


