
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_apprunner_service
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    encryption_configuration = optional(object({
        kms_key = optional(string)
    }))
    health_check_configuration = optional(object({
        protocol = optional(string)
        timeout = optional(number)
        unhealthy_threshold = optional(number)
        healthy_threshold = optional(number)
        interval = optional(number)
        path = optional(string)
    }))
    service_name = optional(string)
    source_configuration = optional(object({
        authentication_configuration = optional(object({
            access_role_arn = optional(string)
            connection_arn = optional(string)
        }))
        auto_deployments_enabled = optional(bool)
        code_repository = optional(object({
            code_configuration = optional(object({
                code_configuration_values = optional(object({
                    build_command = optional(string)
                    port = optional(string)
                    runtime = optional(string)
                    runtime_environment_variables = optional(map(string))
                    start_command = optional(string)
                }))
                configuration_source = optional(string)
            }))
            repository_url = optional(string)
            source_code_version = optional(object({
                type = optional(string)
                value = optional(string)
            }))
        }))
        image_repository = optional(object({
            image_configuration = optional(object({
                port = optional(string)
                runtime_environment_variables = optional(map(string))
                start_command = optional(string)
            }))
            image_identifier = optional(string)
            image_repository_type = optional(string)
        }))
    }))
    tags = optional(map(string))
  })
}

resource "aws_apprunner_service" "this" {
  encryption_configuration = var.values.encryption_configuration
  health_check_configuration = var.values.health_check_configuration
  service_name = var.values.service_name
  source_configuration = var.values.source_configuration
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_apprunner_service.this.arn
}

output "auto_scaling_configuration_arn" {
    value = aws_apprunner_service.this.auto_scaling_configuration_arn
}

output "service_id" {
    value = aws_apprunner_service.this.service_id
}

output "service_url" {
    value = aws_apprunner_service.this.service_url
}

output "status" {
    value = aws_apprunner_service.this.status
}

