######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_ec2_transit_gateway_multicast_domain
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = any object({
    auto_accept_shared_associations = optional(string)
    igmpv2_support = optional(string)
    static_sources_support = optional(string)
    tags = optional(map(string))
    transit_gateway_id = optional(string)
  })
}

resource "aws_ec2_transit_gateway_multicast_domain" "this" {

  {{- if $.Values.auto_accept_shared_associations }}
  auto_accept_shared_associations = var.values.auto_accept_shared_associations
  {{- end }}
  {{- if $.Values.igmpv2_support }}
  igmpv2_support = var.values.igmpv2_support
  {{- end }}
  {{- if $.Values.static_sources_support }}
  static_sources_support = var.values.static_sources_support
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}
  {{- if $.Values.transit_gateway_id }}
  transit_gateway_id = var.values.transit_gateway_id
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_ec2_transit_gateway_multicast_domain.this.arn
}

output "owner_id" {
    value = aws_ec2_transit_gateway_multicast_domain.this.owner_id
}

