######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_appmesh_virtual_router
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

variable "values" {
  type = object({
    mesh_name = optional(string)
    mesh_owner = optional(string)
    name = optional(string)
    spec = optional(list(object({
        listener = optional(list(object({
            port_mapping = optional(list(object({
                protocol = optional(string)
                port = optional(number)
            })))
        })))
    })))
    tags = optional(map(string))
  })
}

resource "aws_appmesh_virtual_router" "this" {

  {{- if $.Values.mesh_name }}
  mesh_name = var.values.mesh_name
  {{- end }}
  {{- if $.Values.mesh_owner }}
  mesh_owner = var.values.mesh_owner
  {{- end }}
  {{- if $.Values.name }}
  name = var.values.name
  {{- end }}
  {{- if $.Values.spec }}
  dynamic "spec" {
    for_each = var.values.spec[*]
    content {
      dynamic "listener" {
        for_each = spec.value.listener[*]
        content {
          dynamic "port_mapping" {
            for_each = listener.value.port_mapping[*]
            content {
              port = port_mapping.value.port
              protocol = port_mapping.value.protocol
            }
          }
        }
      }
    }
  }
  {{- end }}
  {{- if $.Values.tags }}
  tags = var.values.tags
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_appmesh_virtual_router.this.arn
}

output "created_date" {
    value = aws_appmesh_virtual_router.this.created_date
}

output "last_updated_date" {
    value = aws_appmesh_virtual_router.this.last_updated_date
}

output "mesh_owner" {
    value = aws_appmesh_virtual_router.this.mesh_owner
}

output "resource_owner" {
    value = aws_appmesh_virtual_router.this.resource_owner
}

