
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_instance_profile
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.33.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    name = optional(string)
    name_prefix = optional(string)
    path = optional(string)
    role = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_iam_instance_profile" "this" {
  name = var.values.name
  name_prefix = var.values.name_prefix
  path = var.values.path
  role = var.values.role
  tags = var.values.tags
  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "arn" {
    value = aws_iam_instance_profile.this.arn
}

output "create_date" {
    value = aws_iam_instance_profile.this.create_date
}

output "name" {
    value = aws_iam_instance_profile.this.name
}

output "unique_id" {
    value = aws_iam_instance_profile.this.unique_id
}

