
######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_iam_instance_profile
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.32.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    name = optional(string)
    name_prefix = optional(string)
    path = optional(string)
    role = optional(string)
    tags = optional(map(string))
  })
}

resource "aws_iam_instance_profile" "default_resource" {
  name = var.values.name
  name_prefix = var.values.name_prefix
  path = var.values.path
  role = var.values.role
  tags = var.values.tags
}
