######################################################################
# Generated by Tofu-Jet. Please do not manually edit.
# AWS Primitive Module for TF-controller
# Resource: aws_apprunner_custom_domain_association
######################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
}

variable "values" {
  type = object({
    domain_name = optional(string)
    enable_www_subdomain = optional(bool)
    service_arn = optional(string)
  })
}

resource "aws_apprunner_custom_domain_association" "this" {

  {{- if $.Values.domain_name }}
  domain_name = var.values.domain_name
  {{- end }}
  {{- if $.Values.enable_www_subdomain }}
  enable_www_subdomain = var.values.enable_www_subdomain
  {{- end }}
  {{- if $.Values.service_arn }}
  service_arn = var.values.service_arn
  {{- end }}


  {{- if $.Values.count }}
  count = {{ $.Values.count }}
  {{- end }}

  {{- if $.Values.lifecycle }}
  lifecycle {
    {{- if $.Values.lifecycle.create_before_destroy }}
    create_before_destroy = {{ $.Values.lifecycle.create_before_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    prevent_destroy = {{ $.Values.lifecycle.prevent_destroy }}
    {{- end }}
    {{- if $.Values.lifecycle.ignore_changes }}
    ignore_changes = {{ $.Values.lifecycle.ignore_changes }}
    {{- end }}
  }
  {{- end }}
}


output "dns_target" {
    value = aws_apprunner_custom_domain_association.this.dns_target
}

output "service_arn" {
    value = aws_apprunner_custom_domain_association.this.service_arn
}

output "status" {
    value = aws_apprunner_custom_domain_association.this.status
}

